before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5
  - npm install
  - node_modules/.bin/buster-server &
  - sleep 5
  - firefox http://localhost:1111/slaves/646ba36f-671d-4f03-896a-161d7e00648d/browser
  - sleep 5

script:
  - "npm test"

notifications:
  email:
    - sascha@depold.com

language: node_js

node_js:
  - 0.6
